export const QUEST_TYPES = {
  LIST: 'LIST_QUEST',
  MY_QUESTS: 'QUEST/MY',
  ADD: 'ADD_QUESTION',
  GET: 'GET_INFO_QUEST',
  DELETE: 'DELETE_QUEST',
  CREATE: 'CREATE_QUEST',
  START: 'START_QUEST',
  CODE: 'CODE_QUEST',
  JOIN: 'JOIN_QUEST',
  END: 'END_QUEST',
  SET_STATUS: 'SET_STATUS_QUEST',
  TITLE: 'TITLE_QUEST',
  GET_QUIZ_PUBLIC: 'QUIZ_PUBLIC',
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT',
}
