export const ADMIN_TYPE = {
  DELETE: 'ADMIN/DELETE',
  UPDATE: 'ADMIN/UPDATE',
  SET_PAGE: 'ADMIN/SET_PAGE',
  ITEM: 'ADMIN/ITEM',
  GET_QUEST: 'ADMIN/GET_QUEST',
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT',
}
