export const CATEGORY_TYPE = {
  GET: 'CATEGORY/GET',
  DELETE: 'CATEGORY/DELETE',
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT',
}
