export const ADMIN_TYPE = {
  DELETE: 'ADMIN/DELETE',
  GET: 'ADMIN/GET_USER',
  UPDATE: 'ADMIN/UPDATE',
  SET_PAGE: 'ADMIN/SET_PAGE',
  ITEM: 'ADMIN/ITEM',
  CREATECOLLECTION: 'ADMIN/CREATE_COLLECTION',
  GETCOLLECTION: 'ADMIN/GET_COLLECTION',
  GET_COUNT_USER: 'ADMIN/GET_COUNT_USER',
  GET_COUNT_QUIZ: 'ADMIN/GET_COUNT_QUIZ',
  GET_COUNT_GAME: 'ADMIN/GET_COUNT_GAME',
  GET_COUNT_CATEGORY: 'ADMIN/GET_COUNT_CATEGORY',
  GET_ROLE: 'ADMIN/GET_ROLE',
  CREATE_USER: 'ADMIN/CREATE_USER',
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT',
}
