export const ADMIN_TYPE = {
  DELETE: 'ADMIN/DELETE',
  GET: 'ADMIN/GET_USER',
  UPDATE: 'ADMIN/UPDATE',
  SET_PAGE: 'ADMIN/SET_PAGE',
  ITEM: 'ADMIN/ITEM',
  CREATECOLLECTION: 'ADMIN/CREATE_COLLECTION',
  GETCOLLECTION: 'ADMIN/GET_COLLECTION',
}

export const ERROR = {
  NOT_EXIST: 'ERROR/NOT_EXIST',
  DUPLICATE: 'ERROR/DUPLICATE',
}

export const EVENT = {
  RUNNING: 'RUNNING',
  RESULT: 'RESET_RESULT',
}
